
branches:
  only:
    - master
    
environment:
    
  matrix:
    - JOB: "3.7 64-bit"
      MINICONDA: "C:\\Miniconda37-x64"
      PYVERSION: "3.7"

install:

  #
  # Rename existing mingw directory so that scons cannot find it. I'm
  # not sure if this is actually a scons problem but for some reason scons
  # would try and use the default mingw even when it was not in PATH. The
  # build would then fail because the default mingw is 32 bit and this
  # project is 64 bit.
  #
  - "cd c:\\"
  - "rename mingw __mingw"
  - "cd C:\\projects\\storm-analysis"

  # Configure conda Python environment.
  - "%MINICONDA%\\Scripts\\activate base"
  - "conda update --yes -n base conda"
  - "conda --version"
  - "conda create --yes --name saenv python=%PYVERSION%"
  - "conda activate saenv"
  
  # Install dependencies. Why isn't the 'conda' command available in the
  # new virtual environment?
  #
  - "%MINICONDA%\\Scripts\\conda config --add channels conda-forge"
  - "%MINICONDA%\\Scripts\\conda install --yes numpy pytest pytest-runner m2w64-toolchain tifffile scipy h5py astropy matplotlib pillow shapely randomcolor pywavelets scons"

  # Compile C libraries.
  #
  # How long till this breaks? Probably not long. I feel like it should
  # be easier to use 64 bit MinGW..
  #
  - "SET PATH=C:\\mingw-w64\\x86_64-7.2.0-posix-seh-rt_v5-rev1\\mingw64\\bin;%PATH%"
  - "gcc --version"
  - "scons -Q compiler=mingw"
  
  # Check versions and virtual environment.
  - "python --version"
  - "pip -V"

  # Install storm-analysis
  - "python setup.py install"

build: off

test_script:
  - "python setup.py test"

after_test:
  - "python setup.py bdist_wheel"

artifacts:
  - path: dist\*
